rules:
  - id: javascript-pattern-134-insecure-cors-config
    languages:
      - javascript
      - typescript
    severity: ERROR
    message: >
      The cross-domain policy includes wildcards, accepting any domain as valid
      for sharing resources..
    pattern-either:
      - patterns:
        - pattern-inside: |
            cors: {...}
        - pattern: |
            origin: '*'
      
      - pattern: |
          $APP.register(cors);

    metadata:
      category: security
      subcategory:
        - audit
      cwe:
        - "CWE-942: Permissive Cross-domain Policy with Untrusted Domains"
      confidence: HIGH
      likelihood: HIGH
      impact: LOW
